name: Prek Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - '**'
    paths-ignore:
      - '.github/workflows/**'

jobs:
  prek:
    if: github.event_name == 'pull_request' || github.event.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: j178/prek-action@v1
